hostname: memasikov.net

php_error_reporting: E_ALL
php_display_errors: On
php_upload_max_filesize: 40M
php_post_max_size: 50M
php_max_execution_time: 30
php_memory_limit: 128M
php_file_uploads: On
php_max_file_uploads: 20

nginx_certs_folder: '/etc/letsencrypt/archive/memasikov.net/'

nginx_run_user: 'www-data'
nginx_vhosts: [
    { server_name: 'memasikov.net', root: '/var/www/memasikov.net/web', template: 'app'},
]

mysql_bind_address: 127.0.0.1
mysql_client_port: 3306
mysql_mysqld_port: 3306

migrate_db: true
update_archive: false

xdebug_remote_port: 9000
xdebug_remote_host: 10.0.77.1